/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.petshop.popup;

import com.github.sarxos.webcam.Webcam;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import com.petshop.swing.popup.GlassPanePopup;
import com.petshop.ultils.BarcodeListener;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author duat
 */
public class PopupScanBarCode extends javax.swing.JPanel {

    /**
     * Creates new form PopupScanBarCode
     */
    private Webcam webcam;

    public PopupScanBarCode() {
        initComponents();
        startWebcam();
    }

    private BarcodeListener barcodeListener;

    public void setBarcodeListener(BarcodeListener listener) {
        this.barcodeListener = listener;
    }

    private void startWebcam() {
        new Thread(() -> {
            webcam = Webcam.getDefault();
            if (webcam == null) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy webcam!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Chọn độ phân giải cao nhất
            Dimension[] sizes = webcam.getViewSizes();
            webcam.setViewSize(sizes[sizes.length - 1]);

            webcam.open();
            System.out.println("📸 Webcam đang hoạt động, chờ quét mã vạch...");

            while (webcam.isOpen()) {
                BufferedImage image = webcam.getImage();
                if (image != null) {
                    lbWebCam.setIcon(new ImageIcon(image)); // Cập nhật ảnh lên JLabel

                    // Quét mã vạch
                    String barcode = decodeBarcode(image);
                    if (barcode != null) {
                        System.out.println("📌 Mã vạch quét được: " + barcode);

                        // 🔴 Gửi dữ liệu về JFrame cha
                        if (barcodeListener != null) {
                            barcodeListener.onBarcodeListener(barcode);
                        }

                        // 🔴 Tắt webcam ngay sau khi quét
                        webcam.close();
                        System.out.println("❌ Webcam đã tắt.");

                        // ❌ Đóng popup ngay lập tức
                        raven.glasspanepopup.GlassPanePopup.closePopupLast();

                        break; // Thoát vòng lặp sau khi quét xong
                    }
                }
                try {
                    Thread.sleep(100);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        }).start();
    }

    private String decodeBarcode(BufferedImage image) {
        BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(
                new BufferedImageLuminanceSource(image)));
        try {
            Result result = new MultiFormatReader().decode(bitmap);
            return result.getText();
        } catch (NotFoundException e) {
            return null; // Không tìm thấy mã vạch
        }
    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2.dispose();
        super.paintComponent(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbWebCam = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbWebCam, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbWebCam, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbWebCam;
    // End of variables declaration//GEN-END:variables
}
