/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.petshop.form;

import com.petshop.daos.InvoiceDAO;
import com.petshop.daos.InvoiceDetailDAO;
import com.petshop.event.EventCallBack;
import com.petshop.event.EventTextField;
import com.petshop.models.InvoiceDetails;
import com.petshop.models.Invoices;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dut
 */
public class InvoiceManagement extends javax.swing.JPanel {

    /**
     * Creates new form InvoiceManagement
     */
    private InvoiceDAO invoiceDAO;
    private InvoiceDetailDAO invoiceDetailDAO;

    public InvoiceManagement() {
        initComponents();
        this.invoiceDAO = new InvoiceDAO();
        this.invoiceDetailDAO = new InvoiceDetailDAO();
        this.loadTable();
        this.loadTable_InvoiceDetail();
        txtSerch.addEvent(new EventTextField() {
            @Override
            public void onPressed(EventCallBack call) {
                try {
                    for (int i = 0; i < 100; i++) {
                        Thread.sleep(5); //Time Sleep
                    }
                    searchInvoices(txtSerch.getText());
                    txtSerch.setText("");
                    call.done();
                } catch (Exception e) {
                    System.err.println(e);
                }
            }

            @Override
            public void onCancel() {
            }
        });

    }
    
    private void searchInvoices(String text) {
        String keyword = this.txtSerch.getText().trim();
        System.out.println(keyword);

        ArrayList<Invoices> ds = (ArrayList<Invoices>) this.invoiceDAO.search(keyword);
        DefaultTableModel dtm = (DefaultTableModel) this.tbHoaDon.getModel();
        int stt = 1;
        dtm.setRowCount(0);

        for (Invoices invoice : ds) {
            Object[] row = {
                invoice.getId(),
                stt,
                invoice.getInvoiceCode(),
                invoice.getCreatedAt(),
                invoice.getTotalPrice(),
                invoice.getEmployee() != null ? invoice.getEmployee().getEmployeeCode() : "N/A", // Lấy mã nhân viên
                invoice.isPaymentStatus() ? "Đã thanh toán" : "Chưa thanh toán",
                invoice.isPaymentMethod() ? "Chuyển khoản" : "Tiền mặt",
                invoice.getNote(),
                invoice.getCostsIncurred()
            };

            stt++;
            dtm.addRow(row);
        }

        // Ẩn cột ID
        tbHoaDon.getColumnModel().getColumn(0).setMinWidth(0);
        tbHoaDon.getColumnModel().getColumn(0).setMaxWidth(0);
        tbHoaDon.getColumnModel().getColumn(0).setWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        lblKhachHang8 = new javax.swing.JLabel();
        txtSerch1 = new com.petshop.swing.textfield.TextFieldAnimation();
        lblKhachHang9 = new javax.swing.JLabel();
        cbbTrangThai2 = new com.petshop.swing.combobox.ComboboxRounded();
        lblKhachHang10 = new javax.swing.JLabel();
        cbbTrangThai3 = new com.petshop.swing.combobox.ComboboxRounded();
        lblKhachHang11 = new javax.swing.JLabel();
        txtEmail2 = new com.petshop.swing.textfield.TextFieldRounded();
        jButton3 = new javax.swing.JButton();
        lblKhachHang12 = new javax.swing.JLabel();
        txtEmail3 = new com.petshop.swing.textfield.TextFieldRounded();
        jButton4 = new javax.swing.JButton();
        btnDeleteHistory8 = new com.petshop.swing.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKhachHang1 = new com.petshop.swing.table.Table();
        lblKhachHang13 = new javax.swing.JLabel();
        lblKhachHang14 = new javax.swing.JLabel();
        btnDeleteHistory9 = new com.petshop.swing.Button();
        btnDeleteHistory10 = new com.petshop.swing.Button();
        btnDeleteHistory11 = new com.petshop.swing.Button();
        btnDeleteHistory12 = new com.petshop.swing.Button();
        btnDeleteHistory13 = new com.petshop.swing.Button();
        btnDeleteHistory14 = new com.petshop.swing.Button();
        btnDeleteHistory15 = new com.petshop.swing.Button();
        lblKhachHang15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblKhachHang = new javax.swing.JLabel();
        txtSerch = new com.petshop.swing.textfield.TextFieldAnimation();
        lblKhachHang1 = new javax.swing.JLabel();
        lblKhachHang2 = new javax.swing.JLabel();
        lblKhachHang3 = new javax.swing.JLabel();
        txtEmail = new com.petshop.swing.textfield.TextFieldRounded();
        jButton1 = new javax.swing.JButton();
        lblKhachHang4 = new javax.swing.JLabel();
        txtEmail1 = new com.petshop.swing.textfield.TextFieldRounded();
        jButton2 = new javax.swing.JButton();
        btnDeleteHistory = new com.petshop.swing.Button();
        lblKhachHang5 = new javax.swing.JLabel();
        lblKhachHang6 = new javax.swing.JLabel();
        btnDeleteHistory1 = new com.petshop.swing.Button();
        btnDeleteHistory2 = new com.petshop.swing.Button();
        btnDeleteHistory3 = new com.petshop.swing.Button();
        btnDeleteHistory4 = new com.petshop.swing.Button();
        btnDeleteHistory5 = new com.petshop.swing.Button();
        btnDeleteHistory6 = new com.petshop.swing.Button();
        btnDeleteHistory7 = new com.petshop.swing.Button();
        lblKhachHang7 = new javax.swing.JLabel();
        cbbTrangThaiHD = new com.petshop.swing.combobox.Combobox();
        cbbHinhthuc = new com.petshop.swing.combobox.Combobox();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbHoaDon = new com.petshop.swing.table.Table();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbHoaDonChiTiet = new com.petshop.swing.table.Table();

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblKhachHang8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhachHang8.setText("Tìm kiếm hoá đơn: ");

        txtSerch1.setBackground(new java.awt.Color(250, 250, 250));
        txtSerch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerch1ActionPerformed(evt);
            }
        });

        lblKhachHang9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhachHang9.setText("Trạng thái hoá đơn:");

        cbbTrangThai2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả", "Đã kích hoạt", "Chưa kích hoạt" }));
        cbbTrangThai2.setLabeText("Trạng thái");
        cbbTrangThai2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTrangThai2ActionPerformed(evt);
            }
        });

        lblKhachHang10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhachHang10.setText("Hình thức thanh toán:");

        cbbTrangThai3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả", "Đã kích hoạt", "Chưa kích hoạt" }));
        cbbTrangThai3.setLabeText("Hình thức");
        cbbTrangThai3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTrangThai3ActionPerformed(evt);
            }
        });

        lblKhachHang11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhachHang11.setText("Từ:");

        txtEmail2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail2.setLabelText("dd/MM/yyyy");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/petshop/icon/icons8-calendar-24.png"))); // NOI18N

        lblKhachHang12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhachHang12.setText("Đến:");

        txtEmail3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail3.setLabelText("dd/MM/yyyy");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/petshop/icon/icons8-calendar-24.png"))); // NOI18N

        btnDeleteHistory8.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteHistory8.setText("Lọc");
        btnDeleteHistory8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHistory8ActionPerformed(evt);
            }
        });

        tblKhachHang1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "STT", "Mã HD", "Ngày Tạo ", "Ngày thạnh toán", "Thành tiền", "Mã NV", "Tên người nhận", "Địa chỉ", "Tên người ship ", "Ngày ship", "Ngày nhận", "Lý do", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachHang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHang1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKhachHang1);
        if (tblKhachHang1.getColumnModel().getColumnCount() > 0) {
            tblKhachHang1.getColumnModel().getColumn(3).setHeaderValue("Ngày Tạo ");
            tblKhachHang1.getColumnModel().getColumn(4).setHeaderValue("Ngày thạnh toán");
            tblKhachHang1.getColumnModel().getColumn(5).setHeaderValue("Thành tiền");
            tblKhachHang1.getColumnModel().getColumn(6).setHeaderValue("Mã NV");
            tblKhachHang1.getColumnModel().getColumn(7).setHeaderValue("Tên người nhận");
            tblKhachHang1.getColumnModel().getColumn(8).setHeaderValue("Địa chỉ");
            tblKhachHang1.getColumnModel().getColumn(9).setHeaderValue("Tên người ship ");
            tblKhachHang1.getColumnModel().getColumn(10).setHeaderValue("Ngày ship");
            tblKhachHang1.getColumnModel().getColumn(11).setHeaderValue("Ngày nhận");
            tblKhachHang1.getColumnModel().getColumn(12).setHeaderValue("Lý do");
            tblKhachHang1.getColumnModel().getColumn(13).setHeaderValue("Trạng thái");
        }

        lblKhachHang13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhachHang13.setText("Số hoá đơn:");

        lblKhachHang14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhachHang14.setText("...");

        btnDeleteHistory9.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteHistory9.setText("In hoá đơn");
        btnDeleteHistory9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHistory9ActionPerformed(evt);
            }
        });

        btnDeleteHistory10.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteHistory10.setText("Xem chi tiết ");
        btnDeleteHistory10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHistory10ActionPerformed(evt);
            }
        });

        btnDeleteHistory11.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteHistory11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/petshop/icon/export.png"))); // NOI18N
        btnDeleteHistory11.setText("Xuất danh sách ");
        btnDeleteHistory11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHistory11ActionPerformed(evt);
            }
        });

        btnDeleteHistory12.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteHistory12.setText("<<");
        btnDeleteHistory12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHistory12ActionPerformed(evt);
            }
        });

        btnDeleteHistory13.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteHistory13.setText("<");
        btnDeleteHistory13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHistory13ActionPerformed(evt);
            }
        });

        btnDeleteHistory14.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteHistory14.setText(">");
        btnDeleteHistory14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHistory14ActionPerformed(evt);
            }
        });

        btnDeleteHistory15.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteHistory15.setText(">>");
        btnDeleteHistory15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHistory15ActionPerformed(evt);
            }
        });

        lblKhachHang15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhachHang15.setText("...");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(lblKhachHang8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSerch1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(lblKhachHang9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbTrangThai2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblKhachHang10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbTrangThai3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblKhachHang11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblKhachHang12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDeleteHistory8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblKhachHang13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKhachHang14)
                        .addGap(55, 55, 55)
                        .addComponent(btnDeleteHistory12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteHistory13, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblKhachHang15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(btnDeleteHistory14, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteHistory15, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnDeleteHistory9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteHistory10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteHistory11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnDeleteHistory8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKhachHang8)
                            .addComponent(txtSerch1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblKhachHang12)
                                    .addComponent(txtEmail3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbbTrangThai2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblKhachHang9)
                                .addComponent(cbbTrangThai3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblKhachHang10)
                                .addComponent(lblKhachHang11)
                                .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKhachHang13)
                    .addComponent(lblKhachHang14)
                    .addComponent(btnDeleteHistory9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteHistory10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteHistory11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteHistory12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteHistory13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteHistory14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteHistory15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKhachHang15))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        setForeground(new java.awt.Color(204, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hoá đơn");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhachHang.setText("Tìm kiếm hoá đơn: ");

        txtSerch.setBackground(new java.awt.Color(250, 250, 250));
        txtSerch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerchActionPerformed(evt);
            }
        });

        lblKhachHang1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhachHang1.setText("Trạng thái hoá đơn:");

        lblKhachHang2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhachHang2.setText("Hình thức thanh toán:");

        lblKhachHang3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhachHang3.setText("Từ:");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setLabelText("dd/MM/yyyy");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/petshop/icon/icons8-calendar-24.png"))); // NOI18N

        lblKhachHang4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhachHang4.setText("Đến:");

        txtEmail1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail1.setLabelText("dd/MM/yyyy");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/petshop/icon/icons8-calendar-24.png"))); // NOI18N

        btnDeleteHistory.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteHistory.setText("Lọc");
        btnDeleteHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHistoryActionPerformed(evt);
            }
        });

        lblKhachHang5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhachHang5.setText("Số hoá đơn:");

        lblKhachHang6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhachHang6.setText("...");

        btnDeleteHistory1.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteHistory1.setText("In hoá đơn");
        btnDeleteHistory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHistory1ActionPerformed(evt);
            }
        });

        btnDeleteHistory2.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteHistory2.setText("Xem chi tiết ");
        btnDeleteHistory2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHistory2ActionPerformed(evt);
            }
        });

        btnDeleteHistory3.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteHistory3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/petshop/icon/export.png"))); // NOI18N
        btnDeleteHistory3.setText("Xuất danh sách ");
        btnDeleteHistory3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHistory3ActionPerformed(evt);
            }
        });

        btnDeleteHistory4.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteHistory4.setText("<<");
        btnDeleteHistory4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHistory4ActionPerformed(evt);
            }
        });

        btnDeleteHistory5.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteHistory5.setText("<");
        btnDeleteHistory5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHistory5ActionPerformed(evt);
            }
        });

        btnDeleteHistory6.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteHistory6.setText(">");
        btnDeleteHistory6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHistory6ActionPerformed(evt);
            }
        });

        btnDeleteHistory7.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteHistory7.setText(">>");
        btnDeleteHistory7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHistory7ActionPerformed(evt);
            }
        });

        lblKhachHang7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhachHang7.setText("...");

        cbbTrangThaiHD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả", "Đã thanh toán", "Chưa thanh toán" }));
        cbbTrangThaiHD.setLabeText("Trạng thái ");

        cbbHinhthuc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả", "Tiền mặt", "Chuyển khoản" }));
        cbbHinhthuc.setLabeText("Trạng thái ");

        tbHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "STT", "Mã HD", "Ngày Tạo ", "Ngày thạnh toán", "Thành tiền", "Mã NV", "Tên người nhận", "Địa chỉ", "Tên người ship ", "Ngày ship", "Ngày nhận", "Lý do", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHoaDonMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbHoaDon);
        if (tbHoaDon.getColumnModel().getColumnCount() > 0) {
            tbHoaDon.getColumnModel().getColumn(3).setHeaderValue("Ngày Tạo ");
            tbHoaDon.getColumnModel().getColumn(4).setHeaderValue("Ngày thạnh toán");
            tbHoaDon.getColumnModel().getColumn(5).setHeaderValue("Thành tiền");
            tbHoaDon.getColumnModel().getColumn(6).setHeaderValue("Mã NV");
            tbHoaDon.getColumnModel().getColumn(7).setHeaderValue("Tên người nhận");
            tbHoaDon.getColumnModel().getColumn(8).setHeaderValue("Địa chỉ");
            tbHoaDon.getColumnModel().getColumn(9).setHeaderValue("Tên người ship ");
            tbHoaDon.getColumnModel().getColumn(10).setHeaderValue("Ngày ship");
            tbHoaDon.getColumnModel().getColumn(11).setHeaderValue("Ngày nhận");
            tbHoaDon.getColumnModel().getColumn(12).setHeaderValue("Lý do");
            tbHoaDon.getColumnModel().getColumn(13).setHeaderValue("Trạng thái");
        }

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblKhachHang5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKhachHang6)
                        .addGap(55, 55, 55)
                        .addComponent(btnDeleteHistory4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteHistory5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblKhachHang7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteHistory6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteHistory7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnDeleteHistory1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteHistory2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteHistory3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(lblKhachHang)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSerch, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(lblKhachHang1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbbTrangThaiHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblKhachHang2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbbHinhthuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(lblKhachHang3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblKhachHang4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnDeleteHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnDeleteHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKhachHang)
                            .addComponent(txtSerch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblKhachHang4)
                                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblKhachHang1)
                                .addComponent(lblKhachHang2)
                                .addComponent(lblKhachHang3)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbbTrangThaiHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbbHinhthuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDeleteHistory6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeleteHistory7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblKhachHang5)
                        .addComponent(lblKhachHang6)
                        .addComponent(btnDeleteHistory1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeleteHistory2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeleteHistory3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeleteHistory4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeleteHistory5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblKhachHang7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hoá đơn chi tiết ");

        tbHoaDonChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Mã chi tiết sản phẩm", "Tên sản phẩm/Dịch vụ ", "Mã SP/ Dịch vụ ", "Mã thú cưng", "Số lượng", "Đơn giá", "Thành tiền", "Thời gian sử dụng", "Ngày tạo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbHoaDonChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHoaDonChiTietMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbHoaDonChiTiet);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSerchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerchActionPerformed

    private void btnDeleteHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHistoryActionPerformed

    }//GEN-LAST:event_btnDeleteHistoryActionPerformed

    private void btnDeleteHistory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHistory1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteHistory1ActionPerformed

    private void btnDeleteHistory2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHistory2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteHistory2ActionPerformed

    private void btnDeleteHistory3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHistory3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteHistory3ActionPerformed

    private void btnDeleteHistory4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHistory4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteHistory4ActionPerformed

    private void btnDeleteHistory5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHistory5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteHistory5ActionPerformed

    private void btnDeleteHistory6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHistory6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteHistory6ActionPerformed

    private void btnDeleteHistory7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHistory7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteHistory7ActionPerformed

    private void txtSerch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerch1ActionPerformed

    private void cbbTrangThai2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTrangThai2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTrangThai2ActionPerformed

    private void cbbTrangThai3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTrangThai3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTrangThai3ActionPerformed

    private void btnDeleteHistory8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHistory8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteHistory8ActionPerformed

    private void tblKhachHang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHang1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblKhachHang1MouseClicked

    private void btnDeleteHistory9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHistory9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteHistory9ActionPerformed

    private void btnDeleteHistory10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHistory10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteHistory10ActionPerformed

    private void btnDeleteHistory11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHistory11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteHistory11ActionPerformed

    private void btnDeleteHistory12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHistory12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteHistory12ActionPerformed

    private void btnDeleteHistory13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHistory13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteHistory13ActionPerformed

    private void btnDeleteHistory14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHistory14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteHistory14ActionPerformed

    private void btnDeleteHistory15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHistory15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteHistory15ActionPerformed

    private void tbHoaDonChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHoaDonChiTietMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbHoaDonChiTietMouseClicked

    private void tbHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHoaDonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbHoaDonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.petshop.swing.Button btnDeleteHistory;
    private com.petshop.swing.Button btnDeleteHistory1;
    private com.petshop.swing.Button btnDeleteHistory10;
    private com.petshop.swing.Button btnDeleteHistory11;
    private com.petshop.swing.Button btnDeleteHistory12;
    private com.petshop.swing.Button btnDeleteHistory13;
    private com.petshop.swing.Button btnDeleteHistory14;
    private com.petshop.swing.Button btnDeleteHistory15;
    private com.petshop.swing.Button btnDeleteHistory2;
    private com.petshop.swing.Button btnDeleteHistory3;
    private com.petshop.swing.Button btnDeleteHistory4;
    private com.petshop.swing.Button btnDeleteHistory5;
    private com.petshop.swing.Button btnDeleteHistory6;
    private com.petshop.swing.Button btnDeleteHistory7;
    private com.petshop.swing.Button btnDeleteHistory8;
    private com.petshop.swing.Button btnDeleteHistory9;
    private com.petshop.swing.combobox.Combobox cbbHinhthuc;
    private com.petshop.swing.combobox.ComboboxRounded cbbTrangThai2;
    private com.petshop.swing.combobox.ComboboxRounded cbbTrangThai3;
    private com.petshop.swing.combobox.Combobox cbbTrangThaiHD;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblKhachHang1;
    private javax.swing.JLabel lblKhachHang10;
    private javax.swing.JLabel lblKhachHang11;
    private javax.swing.JLabel lblKhachHang12;
    private javax.swing.JLabel lblKhachHang13;
    private javax.swing.JLabel lblKhachHang14;
    private javax.swing.JLabel lblKhachHang15;
    private javax.swing.JLabel lblKhachHang2;
    private javax.swing.JLabel lblKhachHang3;
    private javax.swing.JLabel lblKhachHang4;
    private javax.swing.JLabel lblKhachHang5;
    private javax.swing.JLabel lblKhachHang6;
    private javax.swing.JLabel lblKhachHang7;
    private javax.swing.JLabel lblKhachHang8;
    private javax.swing.JLabel lblKhachHang9;
    private com.petshop.swing.table.Table tbHoaDon;
    private com.petshop.swing.table.Table tbHoaDonChiTiet;
    private com.petshop.swing.table.Table tblKhachHang1;
    private com.petshop.swing.textfield.TextFieldRounded txtEmail;
    private com.petshop.swing.textfield.TextFieldRounded txtEmail1;
    private com.petshop.swing.textfield.TextFieldRounded txtEmail2;
    private com.petshop.swing.textfield.TextFieldRounded txtEmail3;
    private com.petshop.swing.textfield.TextFieldAnimation txtSerch;
    private com.petshop.swing.textfield.TextFieldAnimation txtSerch1;
    // End of variables declaration//GEN-END:variables

    private void loadTable() {
        int stt = 1;
        ArrayList<Invoices> ds = (ArrayList<Invoices>) this.invoiceDAO.getListInvoice();
        DefaultTableModel dtm = (DefaultTableModel) this.tbHoaDon.getModel();
        dtm.setRowCount(0);

        for (Invoices invoice : ds) {
            Object[] row = {
                invoice.getId(),
                stt,
                invoice.getInvoiceCode(),
                invoice.getCreatedAt(),
                invoice.getTotalPrice(),
                invoice.getEmployee() != null ? invoice.getEmployee().getEmployeeCode() : "N/A", // Lấy mã nhân viên
                invoice.isPaymentStatus() ? "Đã thanh toán" : "Chưa thanh toán",
                invoice.isPaymentMethod() ? "Chuyển khoản" : "Tiền mặt",
                invoice.getNote(),
                invoice.getCostsIncurred()
            };

            stt++;
            dtm.addRow(row);
        }

        // Ẩn cột ID
        tbHoaDon.getColumnModel().getColumn(0).setMinWidth(0);
        tbHoaDon.getColumnModel().getColumn(0).setMaxWidth(0);
        tbHoaDon.getColumnModel().getColumn(0).setWidth(0);
    }

    private void loadTable_InvoiceDetail() {
        int stt = 1;
        ArrayList<InvoiceDetails> ds = (ArrayList<InvoiceDetails>) this.invoiceDetailDAO.getListInvoiceDetailProduct();
        DefaultTableModel dtm = (DefaultTableModel) this.tbHoaDon.getModel();
        dtm.setRowCount(0);

        for (InvoiceDetails invoiceDetails : ds) {
            Object[] row = {
                invoiceDetails.getId(),
                stt,
                invoiceDetails.getInvoiceDetailCode(),
                invoiceDetails.getProductOrServiceCode(),
                invoiceDetails.getProductOrServiceName(),
                invoiceDetails.getPet() != null ? invoiceDetails.getPet().getPetCode() : "N/A",
                invoiceDetails.getUsageOrQuantity(),
                invoiceDetails.getPrice(),
                invoiceDetails.getTotal(),
                invoiceDetails.getDuration(),
                invoiceDetails.getCreatedAt()
            };

            stt++;
            dtm.addRow(row);
        }

        // Ẩn cột ID
        tbHoaDon.getColumnModel().getColumn(0).setMinWidth(0);
        tbHoaDon.getColumnModel().getColumn(0).setMaxWidth(0);
        tbHoaDon.getColumnModel().getColumn(0).setWidth(0);
    }
}
